server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - "qa"
  application:
    name: "cards"
  config:
    import: optional:configserver:http://localhost:8071/
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "cards"
    description: "ATP Bank Cards Application"
    version: "1.0.0"

logging:
  level:
    com:
      atp:
        cards: DEBUG